### ISSUE TITLE
feature request: password protected feed

### ISSUE THREAD

**Issue by tristan-k** [remko/atomail#1]
Can you add an option to protect the rss-feed xml with user credentials?

**Comment by remko** [comment]
Hi Tristan,

Password protection of the feed needs to be done elsewhere i'm afraid, it can't be done in the RSS itself. You need to do this on the webserver. How you do this depends on the webserver you are using

Remko

**Comment by tristan-k** [comment]
Thanks! Can you give me a hint? I have a shared hoster with Apache 2.2

**Comment by remko** [comment]
Documentation about authentication in Apache is here: https://httpd.apache.org/docs/2.2/howto/auth.html

However, your hoster needs to allow it. If it does, it will probably boil down to creating a `.htaccess` file in the directory where you host your feed, and adding the necessary `Auth*` directives, in combination with creating a `htpasswd` file outside of your website and pointing to it. But as I said, your hoster needs to allow it, and I'm not sure if it is at all possible to do this as a user. Maybe your hoster has documentation about this.
